default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
development:
  <<: *default
  host: localhost
  database: pic_now_development
  username: pic_now
  password:
test:
  <<: *default
  database: pic_now_test
  username: pic_now
  password:
production:
  <<: *default
  database: pic_now_production
  username: picnow
  host: picnow.cnjjmtsvoavh.us-east-1.rds.amazonaws.com
  port: 5432
  password: <%= ENV['PIC_NOW_DATABASE_PASSWORD'] %>
