default: &default
  adapter: pg
  encoding: utf8
  pool: 5
development:
  <<: *default
  host: localhost
  database: pic_now_development
  password:
test:
  <<: *default
  database: pic_now_test
  password:
production:
  <<: *default
  database: pic_now_production
  username: picnow
  host: picnow.cnjjmtsvoavh.us-east-1.rds.amazonaws.com
  port: 5432
  password: 'df34752dc68f2e5676ddb5716b7078b6'
