development:
  secret_key_base: d507ba88ebabf5a8da75975e747d7985b81a4838c8d4746b41f9d4bde6d115ac8a97ffcec04f846e848d8929f16215af27043eb1ff27a2a317bbbd61bab26771
  s3:
    access_key_id: 'AKIAI7VWRHYGUC54P3ZQ'
    secret_access_key: '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'
    bucket: picnow-development
  twilio:
    sid: 'ACe8da39ac48deb9750026ce4b9eae5f59'
    auth_token: 'f9084e17860f424022dfbf471a221e89'

test:
  secret_key_base: 342df458d91ebea2101d7be132e251f74524c76d15b1c2be1516247b17b037de445b3625293736816752a68c42223d1f6a48b5bcbb7d11fc3f38f6c0812d1f88
  s3:
    access_key_id: 'AKIAI7VWRHYGUC54P3ZQ'
    secret_access_key: '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'
    bucket: picnow-development
  twilio:
    sid: 'ACe8da39ac48deb9750026ce4b9eae5f59'
    auth_token: 'f9084e17860f424022dfbf471a221e89'

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  s3:
    access_key_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
    secret_access_key: <%= ENV['S3_SECRET_ACCESS_KEY'] %>
    bucket: <%= ENV['S3_BUCKET'] %>
  twilio:
    sid: <%= ENV['TWILIO_SID'] %>
    auth_token: <%= ENV['TWILIO_AUTH_TOKEN'] %>
